In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [36]:
df = pd.read_csv('gurgaon_cleaned.csv')

In [37]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1194,5 Bedroom House for sale in Nirvana Country,house,unitech espace,11.50,35494.0,3240.0,Built Up area: 3240 (301.01 sq.m.),5,6,0,not available,"Sector 50, Nirvana Country, Gurgaon, Haryana",1.0,North-West,undefined,"['Sri Radhe Krishna Temple', 'Standard charter...",Best in class property available at sector 50 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3403,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,12.00,37037.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3+,"servant room,pooja room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",3.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Available for sale 5bhk independent house in e...,"['4 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
492,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,1.20,13837.0,867.0,Super Built up area 1510(140.28 sq.m.)Carpet a...,3,3,3,"pooja room,study room","Sector 79 Gurgaon, Gurgaon, Haryana",18.0,North,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Mapsko mountville is an artistic representatio...,"['6 Wardrobe', '1 Stove', '4 AC', '1 Modular K...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1941,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.21,6926.0,1747.0,Super Built up area 1747(162.3 sq.m.),3,3,3+,others,"Multiple Options In, Sector 90 Gurgaon, Gurgao...",29.0,West,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",We have all size and multiple options in all f...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
238,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,1.21,6227.0,1943.0,Super Built up area 1943(180.51 sq.m.)Carpet a...,3,3,3,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",7.0,East,5 to 10 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",M3m woodshire is the a society in sector 107 g...,"['3 Wardrobe', '1 Exhaust Fan', '1 Modular Kit...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction5 out ..."

In [38]:
df.shape

(3940, 20)

In [39]:
df.duplicated().sum()

0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3940 entries, 0 to 3939
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3940 non-null   object
 1   property_type    3940 non-null   object
 2   society          3939 non-null   object
 3   price            3940 non-null   float64
 4   price_per_sqft   3940 non-null   float64
 5   area             3940 non-null   float64
 6   areaWithType     3940 non-null   object
 7   bedRoom          3940 non-null   int64
 8   bathroom         3940 non-null   int64
 9   balcony          3940 non-null   object
 10  additionalRoom   3940 non-null   object
 11  address          3929 non-null   object
 12  floorNum         3919 non-null   float64
 13  facing           2769 non-null   object
 14  agePossession    3939 non-null   object
 15  nearbyLocations  3734 non-null   object
 16  description      3940 non-null   object
 17  furnishDetails   2915 non-null   object
 18  features         3236 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 615.8+ KB

In [41]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                 0
price_per_sqft        0
area                  0
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1171
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1025
features            704
rating             1272
dtype: int64

In [42]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,1.55,7948.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,3,3,"pooja room,study room,servant room,others","H77, Sector 70 Gurgaon, Gurgaon, Haryana",6.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Available flat in shree vardhman victoria in s...,"['1 Fan', '3 Geyser', '1 Microwave', '1 Light'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,0.71,6061.0,1171.0,Super Built up area 1295(120.31 sq.m.)Carpet a...,2,2,3+,others,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17.0,North,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",This is your chance to own a 2 bhk residential...,"['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Safety4 out of 5', 'Lifestyle3 out of 5', 'E..."
2,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.22,13318.0,916.0,Super Built up area 1772(164.62 sq.m.)Built Up...,2,2,3,store room,"Sector 85 Gurgaon, Gurgaon, Haryana",16.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Ss the leaf in sector 85, gurgaon is a ready-T...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf new town heights,1.25,8638.0,1447.0,Carpet area: 1447 (134.43 sq.m.),3,4,3+,servant room,"Sector 90 Gurgaon, Gurgaon, Haryana",0.0,North-West,10+ Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",Located in the popular residential address of ...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Lift(s)', 'Swimming Pool', 'Park', 'Shopping...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,0.95,7929.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,not available,"X03, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Corner flat with full day winter sun in 2 bedr...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction3 out of..."

In [43]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [44]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,Sector 70,1.55,7948.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,3,3,"pooja room,study room,servant room,others","H77, Sector 70 Gurgaon, Gurgaon, Haryana",6.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Available flat in shree vardhman victoria in s...,"['1 Fan', '3 Geyser', '1 Microwave', '1 Light'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,Sector 79,0.71,6061.0,1171.0,Super Built up area 1295(120.31 sq.m.)Carpet a...,2,2,3+,others,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17.0,North,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",This is your chance to own a 2 bhk residential...,"['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Safety4 out of 5', 'Lifestyle3 out of 5', 'E..."
2,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,Sector 85,1.22,13318.0,916.0,Super Built up area 1772(164.62 sq.m.)Built Up...,2,2,3,store room,"Sector 85 Gurgaon, Gurgaon, Haryana",16.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Ss the leaf in sector 85, gurgaon is a ready-T...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf new town heights,Sector 90,1.25,8638.0,1447.0,Carpet area: 1447 (134.43 sq.m.),3,4,3+,servant room,"Sector 90 Gurgaon, Gurgaon, Haryana",0.0,North-West,10+ Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",Located in the popular residential address of ...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Lift(s)', 'Swimming Pool', 'Park', 'Shopping...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,Sector 71,0.95,7929.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,not available,"X03, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Corner flat with full day winter sun in 2 bedr...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction3 out of..."

In [45]:
df['sector'] = df['sector'].str.lower()

In [46]:
df.sample(5)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2845,10 Bedroom House for sale in Sector 11 Gurgaon,house,independent,sector 11,3.50,15555.0,2250.0,Built Up area: 2250 (209.03 sq.m.),10,1,0,not available,"Shivaji Nagar, Sector 11, Gurgaon, Sector 11 G...",1.0,NaN,0 to 1 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...",Looking for a good 10 bhk independent house in...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3730,2 BHK Flat in Sector 95 Gurgaon,flat,rof ananda,sector 95,0.38,58.0,65517.0,Carpet area: 64529 (5994.94 sq.m.),2,2,2,study room,"E1002, Sector 95 Gurgaon, Gurgaon, Haryana",10.0,East,0 to 1 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",Its rera approved and best built quality made ...,NaN,"['Intercom Facility', 'Lift(s)', 'Park']","['Environment4 out of 5', 'Lifestyle4.5 out of..."
755,4 Bedroom House for sale in G block DLF City P...,house,independent,g block dlf city phase 1,5.60,30556.0,1833.0,Plot area 200(167.23 sq.m.),4,3,3+,not available,"G block DLF City Phase 1, Gurgaon, Haryana",3.0,South-West,5 to 10 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",200 square yard independent home for sale in d...,"['6 Wardrobe', '1 Fan', '1 Light', '1 AC', 'No...","['Private Garden / Terrace', 'High Ceiling Hei...",NaN
3141,4 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,sector 109,5.75,16428.0,3500.0,Plot area 272(25.27 sq.m.)Built Up area: 4800 ...,4,4,2,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",272 sq. Yard row house in sobha international ...,"['5 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2759,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,1.07,6524.0,1640.0,Super Built up area 1640(152.36 sq.m.),2,2,3,pooja room,"245, Sector 85 Gurgaon, Gurgaon, Haryana",21.0,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",This lovely 2 bhk apartment/flat in sector 85 ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [47]:
df['sector'].value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    58
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               52
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
sector 66                                                     42
sector 61                                                     42
sector 82                                                     42
dlf phase 2                                                   41
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  26
dlf phase 4                                                   25
sector 112                                                    24
sector 88a                                                    23
sector 111                                                    22
sector 67a                                                    22
dlf phase 3                                                   21
sector 33                                                     20
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 60                                                     15
sector 14                                                     15
sector 63                                                     15
sector 53                                                     14
rajendra park                                                 14
sector 1 imt manesar                                          14
gwal pahari                                                   14
sector 76                                                     14
dlf phase 5                                                   14
sector 3                                                      14
sector 52                                                     14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sohna road                                                    12
sector 31                                                     12
uppals southend                                               12
sector 50                                                     12
sector 38                                                     12
sector 39                                                     12
sector 93                                                     11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 95a                                                     9
sector 55                                                      9
south city 1                                                   9
sector 4                                                       9
ashok vihar phase 2                                            9
sector 57                                                      8
sector 40                                                      8
palam vihar extension                                          8
c block sushant lok phase 1                                    8
dwarka expressway                                              8
mehrauli  road                                                 8
sector 89 a                                                    8
sector 59                                                      8
sector 10a                                                     8
malibu town                                                    8
sector 43                                                      8
surat nagar 1                                                  7
new colony                                                     7
mianwali colony                                                7
sector 51                                                      7
sector 26                                                      7
sector 36 sohna                                                7
sector 58                                                      7
rajiv nagar                                                    6
sector 1                                                       6
jacobpura                                                      6
ashok vihar                                                    6
sector 11                                                      6
jyoti park                                                     6
sector 5                                                       6
dayanand colony                                                5
chakkarpur                                                     5
sector 9                                                       5
sector 80                                                      5
sector 23a                                                     5
arjun nagar                                                    5
new palam vihar                                                5
greenwood city                                                 5
subhash nagar                                                  5
ansal plaza                                                    5
sector 2                                                       5
sector 30                                                      5
sushant lok phase 2                                            5
sector 105                                                     5
saraswati vihar                                                5
manesar                                                        5
sector 28                                                      5
dharam colony                                                  4
garhi harsaru                                                  4
adarsh nagar                                                   4
sector 3a                                                      4
baldev nagar                                                   4
shivaji nagar                                                  4
madanpuri                                                      4
sector 12a                                                     4
valley view estate                                             4
vishnu garden                                                  4
surya vihar                                                    4
imt manesar                                                    4
ravi nagar                                                     4
new                                                            4
sector 6                                                       4
bhim nagar                                                     4
krishna colony                                                 4
bhondsi                                                        4
shivpuri                                                       4
devilal colony                                                 4
suncity                                                        4
sector 17                                                      4
sector 36                                                      4
sector 12                                                      4
laxmi garden                                                   3
sector 17b                                                     3
mg road                                                        3
sector 110 a                                                   3
maruti kunj                                                    3
sector 27                                                      3
patel nagar                                                    3
sector 15                                                      3
sector 73                                                      3
sector 17a                                                     3
prem nagar                                                     3
sector 8                                                       3
sector 23                                                      3
b block sushant lok phase 1                                    3
gandhi nagar                                                   3
a block sushant lok phase 1                                    3
sector 45                                                      3
sector 88b                                                     3
sector 24                                                      2
new palam vihar phase 2                                        2
manohar nagar                                                  2
sushant lok                                                    2
sector-11 sohna                                                2
, delhi ncr                                                    2
sector 21                                                      2
west rajiv nagar                                               2
mayfield garden                                                2
pratap nagar                                                   2
sector 15 part 1                                               2
bissar                                                         2
sector 15 part 2                                               2
golf course road                                               2
iffco chowk                                                    2
shanti nagar                                                   2
hira nagar                                                     2
sheetla colony                                                 2
lajpat nagar                                                   2
bhawani enclave                                                2
new basti                                                      2
sector 41                                                      2
surat nagar phase 2                                            2
shakti nagar                                                   2
new palam vihar phase 1                                        2
block a surya vihar                                            2
farukhnagar                                                    2
acharya puri                                                   2
sector 32                                                      2
samaspur                                                       2
rosewood                                                       2
golf course ext road                                           2
sispal vihar                                                   2
daulatabad                                                     2
mohan nagar                                                    2
rajiv chowk                                                    2
nars                                                           2
surat nagar                                                    2
ambience island                                                2
sector-2 sohna                                                 2
faridabad road                                                 2
shankar vihar                                                  2
sohna  road                                                    2
laxmna vihar, phase 2                                          1
tekchand nagar                                                 1
ats marigold                                                   1
cyber city                                                     1
hno 13 sagar enclave sura                                      1
near sector 1 market                                           1
godrej aria , sector 79 ,                                      1
anand garden, sector-105                                       1
jacobpura near sadar bazar                                     1
jat colony,fazilpur/taj nagar road                             1
sector-5 sheetla colony                                        1
block h ashok vihar phase iii extension                        1
saroop garden rajendra park                                    1
sector 37a                                                     1
ashok vihar phase 3                                            1
nirvana country pocket h                                       1
sector 21a faridabad                                           1
old delhi road, opp sector-14                                  1
gopal nagar, garhi ghasita, sonipat                            1
near khandsa road                                              1
sadar bazar                                                    1
saraswati enclave                                              1
sector 42                                                      1
part 3 sector 5                                                1
block g sector-57                                              1
kanahi                                                         1
khandsa                                                        1
dhankot                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
om nagar                                                       1
garauli kalan                                                  1
sector 37b                                                     1
urban estate, sector 5                                         1
mahalaxmi garden, rajendra place                               1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector-5 sohna                                                 1
ravi nager basai road                                          1
damdma                                                         1
ram nagar                                                      1
sector 5 chowk                                                 1
b1 block sector 57                                             1
ansal's palam vihar                                            1
vir nagar                                                      1
sector 9b                                                      1
sultanpur                                                      1
south city                                                     1
heritage city                                                  1
sector 4 urban estate                                          1
g block dlf city phase 1                                       1
rajiv colony                                                   1
sector 17c                                                     1
v block dlf phase 3                                            1
carterpuri village                                             1
begampur khatola                                               1
kheri                                                          1
near nand hospital                                             1
bhimgarh kheri phase 3                                         1
sai kunj                                                       1
new colony, sector 7                                           1
mahavir pura                                                   1
near euro                                                      1
sector-35 sohna                                                1
huda saraswati vihar                                           1
park view                                                      1
hsiidc plot sector 1 imt manesar                               1
alipur                                                         1
bhora kalan                                                    1
near pataudi chowk                                             1
rattan garden                                                  1
sector 13                                                      1
civil l                                                        1
new jyoti park                                                 1
lucknow                                                        1
shivji park colony                                             1
bptp                                                           1
ashok vihar phase i                                            1
sector-7 hous                                                  1
laxman vihar, railway road,                                    1
Name: sector, dtype: int64

In [48]:
df['sector'].isnull().sum()

0

In [49]:
df['sector'].nunique()

298

In [50]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [51]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [52]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [53]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [54]:
df['sector'].value_counts()

sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     64
sector 107                                                    60
sector 108                                                    58
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 70                                                     53
sector 43                                                     53
sector 37c                                                    53
sector-33 sohna road                                          51
sector 84                                                     51
sector 26                                                     50
sector 49                                                     48
sector 67                                                     48
sector 28                                                     46
sector 103                                                    45
sector 113                                                    43
sector 61                                                     42
sector 66                                                     42
sector 82                                                     42
sector 25                                                     41
sector 7                                                      39
sector 106                                                    38
sector 4                                                      35
sector 99a                                                    32
sector 54                                                     31
sector 12                                                     30
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 57                                                     24
sector 112                                                    24
sector 88a                                                    23
sector 14                                                     23
sector 105                                                    23
sector 24                                                     23
sector 111                                                    22
sector 67a                                                    22
sector 33                                                     20
sector 82a                                                    20
sector 22                                                     20
sector 3                                                      20
sector 78                                                     19
sector 47                                                     19
sector 11                                                     19
sector 63a                                                    18
gwal pahari                                                   18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 110                                                    16
sector 60                                                     15
sector 63                                                     15
sector 1 manesar                                              14
sector 55                                                     14
sector 53                                                     14
sector 52                                                     14
sector 76                                                     14
sector 36a                                                    13
sector 4 phase 2                                              13
sector 9                                                      13
sector 6                                                      13
sector 46                                                     13
sector 31                                                     12
sohna road road                                               12
sector 39                                                     12
sector 38                                                     12
sector 3 phase 3 extension                                    11
sector 93                                                     11
sector 41                                                     11
sector 9a                                                     11
sector 1a manesar                                             10
sector 13                                                     10
sector 95a                                                     9
manesar                                                        9
sector 3 phase 2                                               9
sector 17                                                      8
c block sector 43                                              8
sector 2 extension                                             8
dwarka expressway                                              8
sector 59                                                      8
sector 10a                                                     8
sector 8                                                       8
sector 23                                                      8
sector 40                                                      8
sector 89 a                                                    8
sector 45                                                      8
sector 51                                                      7
sector 36 sohna road                                           7
sector 58                                                      7
sector 5                                                       6
sector 21                                                      6
sector 1                                                       6
sector 23a                                                     5
sector 80                                                      5
sector 30                                                      5
new sector 2                                                   5
sector 12a                                                     4
new                                                            4
sector 36                                                      4
sector 3a                                                      4
sector 88b                                                     3
patel nagar                                                    3
sector 17a                                                     3
b block sector 43                                              3
sector 73                                                      3
sector 17b                                                     3
sector 110 a                                                   3
maruti kunj                                                    3
a block sector 43                                              3
sector 27                                                      3
sector 15                                                      3
sector 15 part 1                                               2
manohar nagar                                                  2
sector 15 part 2                                               2
mohan nagar                                                    2
ambience island                                                2
sispal vihar                                                   2
faridabad road                                                 2
golf course road                                               2
, delhi ncr                                                    2
lajpat nagar                                                   2
iffco chowk                                                    2
sushant lok                                                    2
mayfield garden                                                2
new basti                                                      2
sheetla colony                                                 2
new sector 2 phase 2                                           2
shanti nagar                                                   2
hira nagar                                                     2
golf course ext road                                           2
bissar                                                         2
sector 32                                                      2
shankar vihar                                                  2
sector-11 sohna road                                           2
pratap nagar                                                   2
farukhnagar                                                    2
acharya puri                                                   2
west sector 13                                                 2
bhawani enclave                                                2
daulatabad                                                     2
sector-2 sohna road                                            2
rosewood                                                       2
rajiv chowk                                                    2
samaspur                                                       2
surat nagar phase 2                                            2
surat nagar                                                    2
nars                                                           2
block a sector 21                                              2
sohna road  road                                               2
new sector 2 phase 1                                           2
sec 3 bhim vihar part 1 bhimgher kheri                         1
kanahi                                                         1
block h sector 3 phase iii extension                           1
dhankot                                                        1
sector-5 sheetla colony                                        1
garauli kalan                                                  1
jat colony,fazilpur/taj nagar road                             1
godrej aria , sector 79 ,                                      1
sector 12 near sadar bazar                                     1
sector 21a faridabad                                           1
anand garden, sector-105                                       1
hno 13 sagar enclave sura                                      1
near nand hospital                                             1
laxmna vihar, phase 2                                          1
sector 50 pocket h                                             1
gopal nagar, garhi ghasita, sonipat                            1
sector 42                                                      1
near khandsa road                                              1
near sector 1 market                                           1
cyber city                                                     1
tekchand nagar                                                 1
ats marigold                                                   1
sector 37a                                                     1
mahasector 11, rajendra place                                  1
urban estate, sector 5                                         1
om nagar                                                       1
devi lal colony gali no 12 gurgaon nr omkar public school      1
khandsa                                                        1
block g sector-57                                              1
part 3 sector 5                                                1
saraswati enclave                                              1
sadar bazar                                                    1
sector 37b                                                     1
sector 3 phase 3                                               1
old delhi road, opp sector-14                                  1
saroop garden sector 105                                       1
heritage city                                                  1
ravi nager basai road                                          1
sector 4 urban estate                                          1
sector-7 hous                                                  1
begampur khatola                                               1
kheri                                                          1
sector-5 sohna road                                            1
bhimgarh kheri phase 3                                         1
ram nagar                                                      1
v block sector 24                                              1
sector 17c                                                     1
sector 5 chowk                                                 1
b1 block sector 57                                             1
rajiv colony                                                   1
g block dlf city phase 1                                       1
ansal's sector 2                                               1
vir nagar                                                      1
sector 9b                                                      1
sultanpur                                                      1
south city                                                     1
sector 3 phase i                                               1
carterpuri village                                             1
bptp                                                           1
near pataudi chowk                                             1
near euro                                                      1
sector-35 sohna road                                           1
park view                                                      1
hsiidc plot sector 1 manesar                                   1
alipur                                                         1
damdma                                                         1
bhora kalan                                                    1
mahavir pura                                                   1
shivji park colony                                             1
huda sector 28                                                 1
rattan garden                                                  1
civil l                                                        1
new sector 7                                                   1
sector 7, sector 7                                             1
sai kunj                                                       1
lucknow                                                        1
sector 4, railway road,                                        1
Name: sector, dtype: int64

In [55]:
df['sector'].nunique()

247

In [56]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [57]:
df['sector'].value_counts()

sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      64
sector 107                     60
sector 108                     58
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 70                      53
sector 43                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      46
sector 103                     45
sector 113                     43
sector 66                      42
sector 61                      42
sector 82                      42
sector 25                      41
sector 7                       39
sector 106                     38
sector 4                       35
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 112                     24
sector 57                      24
sector 14                      23
sector 24                      23
sector 105                     23
sector 88a                     23
sector 111                     22
sector 67a                     22
sector 33                      20
sector 82a                     20
sector 22                      20
sector 3                       20
sector 78                      19
sector 47                      19
sector 11                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 55                      14
sector 1 manesar               14
sector 53                      14
sector 76                      14
sector 52                      14
sector 4 phase 2               13
sector 9                       13
sector 46                      13
sector 36a                     13
sector 6                       13
sector 38                      12
sector 39                      12
sector 31                      12
sohna road road                12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 93                      11
sector 13                      10
sector 1a manesar              10
sector 3 phase 2                9
sector 95a                      9
manesar                         9
sector 2 extension              8
sector 45                       8
sector 59                       8
sector 10a                      8
dwarka expressway               8
c block sector 43               8
sector 89 a                     8
sector 8                        8
sector 40                       8
sector 23                       8
sector 17                       8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 1                        6
sector 5                        6
sector 21                       6
new sector 2                    5
sector 23a                      5
sector 80                       5
sector 30                       5
sector 3a                       4
sector 12a                      4
sector 36                       4
new                             4
sector 15                       3
sector 17b                      3
a block sector 43               3
sector 110 a                    3
sector 88b                      3
maruti kunj                     3
sector 73                       3
sector 17a                      3
sector 27                       3
b block sector 43               3
patel nagar                     3
Name: sector, dtype: int64

In [58]:
df['sector'].nunique()

131

In [59]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [60]:
df['sector'].nunique()

114

In [61]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1343,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1661,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
1990,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,2027-06-01 00:00:00,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2316,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [62]:
df.loc[1343,'sector'] = 'sector 37'
df.loc[1661,'sector'] = 'sector 92'
df.loc[1990,'sector'] = 'sector 90'
df.loc[2316,'sector'] = 'sector 76'

In [63]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1267,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2004,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3335,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,NaN
3811,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3858,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']",NaN

In [64]:
df.loc[[1267,2004,3335,3811,3858],'sector'] = 'sector 110'

In [65]:
df.shape

(3785, 21)

In [66]:
df.duplicated().sum()

0

In [67]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,sector 70,1.55,7948.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,3,3,"pooja room,study room,servant room,others","H77, Sector 70 Gurgaon, Gurgaon, Haryana",6.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Available flat in shree vardhman victoria in s...,"['1 Fan', '3 Geyser', '1 Microwave', '1 Light'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,sector 79,0.71,6061.0,1171.0,Super Built up area 1295(120.31 sq.m.)Carpet a...,2,2,3+,others,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17.0,North,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",This is your chance to own a 2 bhk residential...,"['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Safety4 out of 5', 'Lifestyle3 out of 5', 'E..."
2,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,1.22,13318.0,916.0,Super Built up area 1772(164.62 sq.m.)Built Up...,2,2,3,store room,"Sector 85 Gurgaon, Gurgaon, Haryana",16.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Ss the leaf in sector 85, gurgaon is a ready-T...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 90 Gurgaon,flat,dlf new town heights,sector 90,1.25,8638.0,1447.0,Carpet area: 1447 (134.43 sq.m.),3,4,3+,servant room,"Sector 90 Gurgaon, Gurgaon, Haryana",0.0,North-West,10+ Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",Located in the popular residential address of ...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Lift(s)', 'Swimming Pool', 'Park', 'Shopping...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,sector 71,0.95,7929.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,not available,"X03, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Corner flat with full day winter sun in 2 bedr...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction3 out of..."

In [68]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [69]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
606,flat,shree vardhman flora,sector 90,0.66,5076.0,1300.0,Super Built up area 1300(120.77 sq.m.)Carpet a...,2,2,3,study room,4.0,North-East,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe..."
1206,flat,tata primanti,sector 72,5.00,11111.0,4500.0,Built Up area: 4500 (418.06 sq.m.)Carpet area:...,4,4,3+,"pooja room,study room,servant room,others",2.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","['4 Wardrobe', '6 Fan', '7 Geyser', '1 Stove',...","['Centrally Air Conditioned', 'Water purifier'..."
1246,flat,chd avenue,sector 71,0.82,7083.0,1158.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,6.0,NaN,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",[],NaN
3711,flat,krisumi waterfall residences,sector 36a,2.30,15551.0,1479.0,Built Up area: 1479 (137.4 sq.m.),2,2,2,not available,23.0,NaN,undefined,"['Elan Miracle Mall', 'Dwarka Expy', 'NH 48', ...",NaN,NaN
2333,house,independent,sector 43,2.55,13178.0,1935.0,Built Up area: 215 (179.77 sq.m.),3,3,2,not available,3.0,NaN,1 to 5 Year Old,"['Mg road metro station', 'Iffco chowk metro s...","['5 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Centrally Ai..."

In [70]:
df.to_csv('final_cleaned_v1.csv',index=False)